# fly.toml app configuration file generated for adguard-green on 2024-07-26T22:28:48+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'adguard-green'
primary_region = 'sin'

[build]

# 53     : TCP, UDP : DNS
# 67     :      UDP : DHCP (server)
# 68     :      UDP : DHCP (client)
# 80     : TCP      : HTTP (main)
# 443    : TCP, UDP : HTTPS, DNS-over-HTTPS (incl. HTTP/3), DNSCrypt (main)
# 853    : TCP, UDP : DNS-over-TLS, DNS-over-QUIC
# 3000   : TCP, UDP : HTTP(S) (alt, incl. HTTP/3)
# 5443   : TCP, UDP : DNSCrypt (alt)
# 6060   : TCP      : HTTP (pprof)

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  internal_port = 443
  protocol = "tcp"
  [[services.ports]]
    port = 443

[[services]]
  internal_port = 443
  protocol = "udp"
  [[services.ports]]
    port = 443

[[services]]
  internal_port = 853
  protocol = "tcp"
  [[services.ports]]
    port = 853

[[services]]
  internal_port = 853
  protocol = "udp"
  [[services.ports]]
    port = 853

[[services]]
  internal_port = 5443
  protocol = "tcp"
  [[services.ports]]
    port = 5443

[[services]]
  internal_port = 5443
  protocol = "udp"
  [[services.ports]]
    port = 5443

[[services]]
  internal_port = 6060
  protocol = "tcp"
  [[services.ports]]
    port = 6060

[[services]]
  internal_port = 53
  protocol = "tcp"
  [[services.ports]]
    port = 53

[[services]]
  internal_port = 53
  protocol = "udp"
  [[services.ports]]
    port = 53

[[services]]
  internal_port = 3000
  protocol = "tcp"
  [[services.ports]]
    port = 3000

[[services]]
  internal_port = 3000
  protocol = "udp"
  [[services.ports]]
    port = 3000


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
