app = "adguard"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  image = "ghcr.io/webees/adguard"

[mounts]
  source = "app_data"
  destination = "/data"

[http_service]
  internal_port = 80
  force_https = true
  min_machines_running = 1

[checks]
  [checks.health]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/assets/favicon.png"
    port = 80
    timeout = "10s"
    type = "http"
